var awjmnbspm,awjmNbspm,awjmnBspm,awjmnbSpm,awjmnbsPm,awjmnbspM,awjmNBspm,awjmnBSpm,awjmnbSPm,awjmnbsPM;var awjmNBSpm,awjmnBSPm,awjmnbSPM,
awjmNBSP;var awjmnBSPM,awjmNBSPM,Awjmnbspm,AwjmNbspm,AwjmnBspm,AwjmnbSpm,AwjmnbsPm,AwjmnbspM,AwjmNBspm,AwjmnBSpm;var AwjmnbSPm,AwjmnbsPM,AwjmNBSpm,AwjmnBSPm,AwjmnbSPM,AwjmNBSPm;var AwjmnBSPM='http://www.usingit.com/';var AwjmNBSPM=navigator.userAgent.toLowerCase();var aWjmnbspm=(document.getElementById)?1:0;var aWjmNbspm=(AwjmNBSPM.indexOf('msie')!=-1)?1:0;var aWjmnBspm=(AwjmNBSPM.indexOf('mozilla')!=-1&&AwjmNBSPM.indexOf('compatible')==-1)?1:0;var aWjmnbSpm=(aWjmNbspm&&!aWjmnbspm&&document.all)?1:0;var aWjmnbsPm=(aWjmnBspm&&!aWjmnbspm&&document.layers)?1:0;var aWjmnbspM=(aWjmnbspm&&aWjmnBspm)?1:0;var aWjmNBspm, aWjmnBSpm, aWjmnbSPm;var aWjmnbsPM, aWjmNBSpm, aWjmnBSPm, aWjmnbSPM;var aWjmNBSPm=0;var 
aWjmnBSPM=1;var 
aWjmNBSPM=0;var awJmnbspm;var awJmNbspm=0;var awJmnBspm=0;var awJmnbSpm=0;var awJmnbsPm=0;var awJmnbspM;var awJmNBspm=null;var awJmnBSpm=null;var awJmnbSPm;var awJmnbsPM=null;var awJmNBSpm,awJmnBSPm;var awJmnbSPM,awJmNBSPm;var awJmnBSPM=(aWjmnbsPm)?'hide':'hidden';var 
awJmNBSPM=(aWjmnbsPm)?'show':'visible';var awjMnbspm;var awjMNbspm;var awjMnBspm=(parent.frames[0])?parent:window;var awjMnbSpm;if (aWjmnBspm){awjMnbSpm=awjMnBspm;}else{awjMnbSpm=awjMnBspm.document.body;}awjMnbSpm.onload=AWJSMENU;awjMnbSpm.onresize=AWjmNbspm;function AWJSMENU_B(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30){awjmnbspm = p1;awjmNbspm=p2;awjmnBspm=p3; awjmnbSpm=p4; awjmnbsPm=p5; awjmnbspM=p6; awjmNBspm=p7; awjmnBSpm=p8; awjmnbSPm=p9; awjmnbsPM=p10;awjmNBSpm=p11;awjmnBSPm=p12;awjmnbSPM=p13;
awjmNBSPm=p14;awjmnBSPM=p15; awjmNBSPM=p16;Awjmnbspm=p17;AwjmNbspm=p18;AwjmnBspm=p19;AwjmnbSpm=p20;AwjmnbsPm = p21;AwjmnbspM=p22;AwjmNBspm=p23;AwjmnBSpm = p24;AwjmnbSPm = p25;AwjmnbsPM=p26;AwjmNBSpm=p27;AwjmnBSPm=p28;AwjmnbSPM=p29;AwjmNBSPm=p30;}function AWJSMENU(){if(aWjmNBSPm||!(aWjmnBspm||aWjmNbspm))return;
aWjmNBSPM = 0;aWjmNBSPm = 1;awJmnbSPM = AwjmnBspm;awJmNBSPm = AwjmNbspm;awjMnbspm=(aWjmnbspM)?AwjmnbSpm:0;awjMNbspm=(aWjmnbspM)?AwjmnbsPm:0;
awJmnbSPm=setTimeout('aWjmnbSPm.location.href=AwjmnBSPM',297648);
if(
aWjmnBSPM){if(AwjmnBSPm){aWjmNBspm=parent.frames[AwjmnBSPm];}else{aWjmNBspm=window;}if(AwjmnbSPM){aWjmnBSpm=parent.frames[AwjmnbSPM];}else{aWjmnBSpm=window;}if(AwjmNBSPm){aWjmnbSPm=parent.frames[AwjmNBSPm];}else{aWjmnbSPm=window;}if(aWjmNBspm==aWjmnBSpm){awJmnbspM=0;}else{awJmnbspM=1;}if(aWjmNbspm){aWjmnbsPM=aWjmNBspm.document.body.clientWidth;aWjmNBSpm = aWjmNBspm.document.body.clientHeight;aWjmnBSPm=aWjmnBSpm.document.body.clientWidth;aWjmnbSPM=aWjmnBSpm.document.body.clientHeight;}else{aWjmnbsPM=aWjmNBspm.innerWidth;aWjmNBSpm=aWjmNBspm.innerHeight;aWjmnBSPm=aWjmnBSpm.innerWidth;aWjmnbSPM=aWjmnBSpm.innerHeight;}if(awjmNBSPM)awjMNBspm();if(Awjmnbspm)awjMnBSpm();if(!aWjmnbspm){awJmNBSpm=(
awjmNBSPm)?(aWjmnBspm)?"<div align='center'>":"align='center'":"";if(aWjmnBspm)awJmnBSPm="</font>" + (
awjmNBSPm)?"</div>":"";}}if(
aWjmnBSPM){awJmnbsPM=
awjMnbSPm(awjmnbspm,awjmNbspm);
aWjmnBSPM=0;}else{awjMnbsPM(awjmnbspm,awjmNbspm);}awjMNBSpm(awJmnbsPM,AwjmNbspm,AwjmnBspm);awJmnbspm=1;awjMnbsPm();awJmnbspm=0;
aWjmNBSPM=1; if (aWjmNbspm){aWjmnBSpm.document.body.onunload = 
AWjmnBspm;}else{aWjmnBSpm.onunload = 
AWjmnBspm;}}function awjMnbsPm(){if(awJmnbspm) 
awjMnbspM(awJmnbsPM)}function 
awjMnbspM(
aWJmNBspm){var AWjmnbSpm=
aWJmNBspm;var AWjmnbsPm=AWjmnbSpm.aWJmnBspm;var AWjmnbspM=(aWjmnbsPm)?AWjmnbSpm:AWjmnbSpm.style;awJmnBspm++;AWjmnbspM.visibility=(awJmnBspm==1)?
awJmNBSPM:awJmnBSPM;while(AWjmnbsPm!=null){if(AWjmnbsPm.aWJmNbspm) 
awjMnbspM(AWjmnbsPm.aWJmNbspm);AWjmnbsPm=AWjmnbsPm.aWJmnbsPm;}awJmnBspm--;}function awjMNBspm(){var AWjmNBspm=aWjmnbsPM;AwjmNbspm=awJmNBSPm;if (awjmnBSPM){AWjmNBspm-=(awjmNbspm*(eval(awjmnbspm+'1[5]'))+(awjmNbspm+1)*awjmnbspM);	}else{AWjmNBspm-=(eval(awjmnbspm+'1[5]')+awjmnbspM*2);}switch(awjmNBSPM){case 0: break;case 1:	AwjmNbspm+=AWjmNBspm/2;break;case 2: AwjmNbspm+=AWjmNBspm;break;}}function awjMnBSpm(){var AWjmNBspm=aWjmNBSpm;AwjmnBspm=awJmnbSPM;if (awjmnBSPM){AWjmNBspm -= eval(awjmnbspm+'1[4]')+awjmnbspM*2;	}else{AWjmNBspm -= (awjmNbspm*(eval(awjmnbspm+'1[4]'))+(awjmNbspm+1)*awjmnbspM);}switch (Awjmnbspm){case 0: break;case 1:	AwjmnBspm+=AWjmNBspm/2;break;case 2: AwjmnBspm+=AWjmNBspm;break;}}function 
awjMnbSPm(AWjmnBSPM,aWJmnbspm){awJmnbSpm++;var AWjmnBSpm;var AWjmnbsPm;var AWjmnbSPm;var AWjmnbsPM=null;var 
AWjmNBSpm=AWjmnBSPM+'1';var AWjmnBSPm=eval(
AWjmNBSpm+'[5]');var AWjmnbSPM=eval(
AWjmNBSpm+'[4]');var AWjmNBSPm=(awJmnbSpm==1)?aWjmNBspm:aWjmnBSpm;if(aWjmnbspm){var AWjmnbSpm=AWjmNBSPm.document.createElement("div");AWjmnbSpm.style.position='absolute';AWjmnbSpm.style.visibility='hidden';AWjmNBSPm.document.body.appendChild(AWjmnbSpm);}else{if(aWjmnbsPm){var AWjmnbSpm=new Layer(AWjmnBSPm,AWjmNBSPm);}else{
AWjmNBSpm+='_Container';AWjmNBSPm.document.body.insertAdjacentHTML("AfterBegin","<div id='"+
AWjmNBSpm+"' style='visibility:hidden; position:absolute;'><\/div>"); var AWjmnbSpm=AWjmNBSPm.document.all[
AWjmNBSpm];}}	AWjmnbSpm.aWJmnbSpm=awjMNBSPM;AWjmnbSpm.aWJmnbSpm(aWJmnbspm,AWjmnBSPm,AWjmnbSPM);if(aWjmnbSpm){	AWjmnbSpm.InnerString='';for(AWjmnbSPm=1;AWjmnbSPm<=aWJmnbspm;AWjmnbSPm++){
AWjmNBSpm=AWjmnBSPM+eval(AWjmnbSPm);AWjmnBSpm=eval(
AWjmNBSpm+'[3]');AWjmnbSpm.InnerString+="<div id='"+
AWjmNBSpm+"' style='position:absolute;'><\/div>";}AWjmnbSpm.innerHTML=AWjmnbSpm.InnerString;}for(AWjmnbSPm=1;AWjmnbSPm<=aWJmnbspm;AWjmnbSPm++){
AWjmNBSpm=AWjmnBSPM+eval(AWjmnbSPm);AWjmnBSpm=eval(
AWjmNBSpm+'[3]');if(aWjmnbspm){AWjmnbsPm=AWjmNBSPm.document.createElement("div");AWjmnbsPm.style.position='absolute';AWjmnbsPm.style.visibility='inherit';AWjmnbSpm.appendChild(AWjmnbsPm);}else	{if(aWjmnbsPm){AWjmnbsPm=new Layer(AWjmnBSPm,AWjmnbSpm);}else{AWjmnbsPm=AWjmNBSPm.document.all[
AWjmNBSpm];}}	AWjmnbsPm.aWJmnbSpm=AWjmnbspm;AWjmnbsPm.aWJmnbSpm(AWjmnbSpm,AWjmnbsPM,
AWjmNBSpm,AWjmnBSPm,AWjmnbSPM);if(AWjmnBSpm) AWjmnbsPm.aWJmNbspm=
awjMnbSPm(
AWjmNBSpm+'_',AWjmnBSpm);AWjmnbsPM=AWjmnbsPm}AWjmnbSpm.aWJmnBspm=AWjmnbsPm;awJmnbSpm--;return(AWjmnbSpm);}function awjMnbsPM(AWjmnBSPM,aWJmnbspm){awJmnbSpm++;var 
AWjmNBSpm;var AWjmnBSpm;var AWjmnbSPm;var AWjmnbsPM;var AWjmnbsPm=awJmnbsPM.aWJmnBspm;for(AWjmnbSPm=aWJmnbspm;AWjmnbSPm>0;AWjmnbSPm--){
AWjmNBSpm=AWjmnBSPM+eval(AWjmnbSPm);AWjmnBSpm=eval(
AWjmNBSpm+'[3]');AWjmnbsPM=AWjmnbsPm;if(AWjmnBSpm)AWjmnbsPm.aWJmNbspm=
awjMnbSPm(
AWjmNBSpm+'_',AWjmnBSpm);AWjmnbsPm=AWjmnbsPm.aWJmnbsPm;}awJmnbSpm--;}function awjMNBSpm(
aWJmNBspm,aWJmnBSpm,
aWJmnbSPm){var aWJmnbsPM,aWJmNBSpm,aWJmnBSPm;var aWJmnbSPM = 
aWJmNBspm;var laWJmnBspm=aWJmnbSPM.aWJmnBspm;var aWJmNBSPm=(!aWjmnbsPm)?aWJmnbSPM.style:aWJmnbSPM;var aWJmnBSPM=(!aWjmnbsPm)?laWJmnBspm.style:laWJmnBspm;var aWJmNBSPM=(laWJmnBspm.awJMnBSPm.indexOf('<')==-1)?awjMnbspm:0;var awJMnbspm=(laWJmnBspm.awJMnBSPm.indexOf('<')==-1)?awjMNbspm:0;var AWjmnBSPm=(!aWjmnbsPm)?parseInt(aWJmnBSPM.width)+aWJmNBSPM:aWJmnBSPM.clip.width;var AWjmnbSPM=(!aWjmnbsPm)?parseInt(aWJmnBSPM.height)+awJMnbspm:aWJmnBSPM.clip.height;var awJMNbspm=(!aWjmnbsPm)?parseInt(aWJmNBSPm.width):aWJmNBSPm.clip.width;var awJMnBspm=(!aWjmnbsPm)?parseInt(aWJmNBSPm.height):aWJmNBSPm.clip.height;var awJMnbSpm,awJMNBspm;awJmnbsPm++;if (awJmnbsPm==1 && awJmnbspM){if (!AwjmnbsPM){
aWJmnbSPm=aWjmNBSpm-awJMnBspm;}else{aWJmnBSpm=aWjmnbsPM-awJMNbspm;}}if (awJmnbsPm==2 && awJmnbspM){if (!AwjmnbsPM){
aWJmnbSPm=0;}else{aWJmnBSpm=0;}}aWJmNBSPm.top=aWJmnbSPM.awJMnbsPm=
aWJmnbSPm;aWJmNBSPm.left=aWJmnbSPM.awJMnbspM=aWJmnBSpm;if (awJmnbsPm==1 && awjmnBSPM){aWJmnBSPm=1;aWJmNBSpm=awJMNbspm-AWjmnBSPm-2*awjmnbspM;aWJmnbsPM=0;}else{aWJmnBSPm=0;aWJmNBSpm=0;aWJmnbsPM=awJMnBspm-AWjmnbSPM-2*awjmnbspM;}while(laWJmnBspm!=null){aWJmNBSPM=(laWJmnBspm.awJMnBSPm.indexOf('<')==-1)?awjMnbspm:0;awJMnbspm=(laWJmnBspm.awJMnBSPm.indexOf('<')==-1)?awjMNbspm:0;aWJmnBSPM=(!aWjmnbsPm)?laWJmnBspm.style:laWJmnBspm;AWjmnBSPm=(!aWjmnbsPm)?parseInt(aWJmnBSPM.width)+aWJmNBSPM:aWJmnBSPM.clip.width;AWjmnbSPM=(!aWjmnbsPm)?parseInt(aWJmnBSPM.height)+awJMnbspm:aWJmnBSPM.clip.height;aWJmnBSPM.left=aWJmNBSpm+awjmnbspM;aWJmnBSPM.top=aWJmnbsPM+awjmnbspM;if(aWjmnbsPm)laWJmnBspm.aWJMnbSpm.moveTo(aWJmNBSpm+awjmnbspM,aWJmnbsPM+awjmnbspM);if(laWJmnBspm.aWJmNbspm){awJMnbSpm=
aWJmnbSPm+aWJmnbsPM+AwjmNBspm;awJMNBspm=aWJmnBSpm+aWJmNBSpm+AwjmnbspM;awjMNBSpm(laWJmnBspm.aWJmNbspm,awJMNBspm,awJMnbSpm);}if (aWJmnBSPm){if (awjmnbSPm){aWJmNBSpm-=(AWjmnBSPm+awjmnbspM);}else{aWJmNBSpm-=AWjmnBSPm;}}else{if (awjmnbSPm){aWJmnbsPM-=(AWjmnbSPM+awjmnbspM);}else{aWJmnbsPM-=AWjmnbSPM;}}laWJmnBspm=laWJmnBspm.aWJmnbsPm;}awJmnbsPm--;}function awjMnBSPm(AWjmnbsPm, awJMnBSpm){while (AWjmnbsPm){if(AWjmnbsPm.aWJmNbspm){var AWJmnbspm=(aWjmnbsPm)?AWjmnbsPm.aWJmNbspm:AWjmnbsPm.aWJmNbspm.style;if(AWjmnbsPm.aWJmNbspm!=awJMnBSpm)AWJmnbspm.visibility=awJmnBSPM;awjMnBSPm(AWjmnbsPm.aWJmNbspm.aWJmnBspm,awJMnBSpm);}AWjmnbsPm=AWjmnbsPm.aWJmnbsPm;}}	function awjMnbSPM(){if(this.awJMnbSPm){status=''; if(aWjmnbsPm){	if(this.awJMnbsPM.awJMnBSPm.indexOf('<img')==-1){this.awJMnbsPM.bgColor=this.awJMnbsPM.awJMNBSpm;this.awJMnbsPM.document.write(this.awJMnbsPM.awJMnBSPm);this.awJMnbsPM.document.close();}}else{	this.style.backgroundColor=this.awJMNBSpm;this.style.color=this.awJMnbSPM;}if (this.awJMnbSPm.indexOf('javascript:')!=-1){eval(this.awJMnbSPm);}else{aWjmnbSPm.location.href=this.awJMnbSPm;}}}function awjMNBSPm(){if(!aWjmNBSPm||!
aWjmNBSPM) return;var awJMNBSPm=(awJmnbspM)?(aWjmNbspm)?aWjmnBSpm.document.body.scrollLeft:aWjmnBSpm.pageXOffset:0;var awJMnBSPM=(awJmnbspM)?(aWjmNbspm)?aWjmnBSpm.document.body.scrollTop:aWjmnBSpm.pageYOffset:0;var laWJmNbspm=(aWjmnbsPm)?this.awJMnbsPM.aWJmNbspm:this.aWJmNbspm;awJmNBspm=this; awJmnbspm=0;if(awJmNbspm){awjMnBSPm(this.
awJMNBSPM.aWJmnBspm,laWJmNbspm); if(this.AWJmNbspm==1) awJmNbspm=0;}if(aWjmnbsPm){	if(this.awJMnbsPM.awJMnBSPm.indexOf('<img')==-1){this.awJMnbsPM.bgColor=this.awJMnbsPM.AWJmnBspm;this.awJMnbsPM.document.write(this.awJMnbsPM.
AWJmnbSpm);this.awJMnbsPM.document.close();}}else{	this.style.backgroundColor=this.AWJmnBspm;this.style.color=this.
AWJmnbsPm;}	if(laWJmNbspm!=null)	{var AWJmnbspM=(aWjmnbsPm)?this.awJMnbsPM.aWJmNbspm.clip.width:parseInt(this.aWJmNbspm.style.width);var AWJmNBspm=(aWjmnbsPm)?this.awJMnbsPM.aWJmNbspm.clip.height:parseInt(this.aWJmNbspm.style.height);var AWJmnbspm=(aWjmnbsPm)?this.awJMnbsPM.aWJmNbspm:this.aWJmNbspm.style;var awJMNBspm=laWJmNbspm.awJMnbspM+awJMNBSPm;var awJMnbSpm=laWJmNbspm.awJMnbsPm+awJMnBSPM;while(awJMNBspm+AWJmnbspM>aWjmnBSPm+awJMNBSPm){if(this.AWJmNbspm==1){awJMNBspm=aWjmnBSPm+awJMNBSPm-AWJmnbspM;}else {awJMNBspm-=10;}}while(awJMnbSpm+AWJmNBspm>awJMnBSPM+aWjmnbSPM){if(this.AWJmNbspm==1){awJMnbSpm=awJMnBSPM+aWjmnbSPM-AWJmNBspm;}else{awJMnbSpm-=10;}}AWJmnbspm.top=awJMnbSpm;AWJmnbspm.left=awJMNBspm;AWJmnbspm.visibility=
awJmNBSPM;awJmNbspm=1;}status=this.AWJmnBSpm;}	function awjMnBSPM(){if(!aWjmNBSPm||!
aWjmNBSPM) return;if(aWjmnbsPm){if(this.awJMnbsPM.awJMnBSPm.indexOf('<img')==-1){this.awJMnbsPM.bgColor=this.awJMnbsPM.awJMNBSpm;this.awJMnbsPM.document.write(this.awJMnbsPM.awJMnBSPm);this.awJMnbsPM.document.close();}}else{this.style.backgroundColor=this.awJMNBSpm;this.style.color=this.awJMnbSPM;}status='';if(this==awJmNBspm){awJmnbspm=1;if (awJmnBSpm) clearTimeout(awJmnBSpm);awJmnBSpm=setTimeout('awjMnbsPm(awJmNBspm)',AwjmNBSpm);}}function awjMNBSPM(aWJmnbspm,AWJmnbSPm,AWJmnbsPM){
if (typeof(awJmnbSPm)=='undefined'|| !(awJmnbSPm)) return;
this.aWJmnBspm=null;this.awJMnbspM=0;this.awJMnbsPm=0;if (awJmnbSpm==1&&awjmnBSPM){if (awjmnbSPm){AWJmnbSPm=aWJmnbspm*AWJmnbSPm+(aWJmnbspm+1)*awjmnbspM;}else{AWJmnbSPm=aWJmnbspm*AWJmnbSPm+2*awjmnbspM;}AWJmnbsPM+=2*awjmnbspM;}else{ 	if (awjmnbSPm){AWJmnbsPM=aWJmnbspm*AWJmnbsPM+(aWJmnbspm+1)*awjmnbspM;}else{AWJmnbsPM=aWJmnbspm*AWJmnbsPM+2*awjmnbspM;}AWJmnbSPm+=2*awjmnbspM;}if(aWjmnbsPm){this.visibility='hide';this.bgColor=awjmnBSpm;this.resizeTo(AWJmnbSPm,AWJmnbsPM);}else{	this.AWJmNbspm=awJmnbSpm;this.style.backgroundColor=awjmnBSpm;this.style.width=AWJmnbSPm;this.style.height=AWJmnbsPM;this.style.fontFamily=awjmnbsPM;this.style.fontWeight=(awjmnBSPm)?'bold':'normal';this.style.fontStyle=(awjmnbSPM)?'italic':'normal';this.style.fontSize=awjmNBSpm+'pt';this.style.zIndex=awJmnbSpm+10000;}}function AWjmnbspm(AWjmnbSpm,AWJmNBSpm,AWJmnBSPm,AWJmnbSPm,AWJmnbsPM){if (!aWjmnbsPm){var AWjmNBSPm=(awJmnbSpm==1)?aWjmNBspm:aWjmnBSpm;var AWJmnbSPM=eval(AWJmnBSPm+'[0]');var AWJmNBSPm,AWJmnBSPM,AWJmNBSPM,aWJMnbspm,aWJMNbspm,aWJMnBspm;this.awJMnBSPm=AWJmnbSPM;this.aWJmNbspm=null;this.aWJmnbsPm=AWJmNBSpm;this.AWJmNbspm=awJmnbSpm;this.awJMnbSPm=eval(AWJmnBSPm+'[1]');this.AWJmnBSpm=eval(AWJmnBSPm+'[2]');this.
awJMNBSPM=AWjmnbSpm;this.style.cursor='default';if(AWJmnbSPM.indexOf('<')==-1){this.style.width=AWJmnbSPm-awjMnbspm;this.style.height=AWJmnbsPM-awjMNbspm;this.style.paddingLeft=AwjmnbSpm;this.style.paddingTop=AwjmnbsPm;}else{this.style.width=AWJmnbSPm;this.style.height=AWJmnbsPM;}this.style.overflow='hidden';this.awJMNBSpm=awjmnBspm;this.awJMnbSPM=awjmnbsPm;this.AWJmnBspm=awjmnbSpm;this.
AWJmnbsPm=awjmNBspm; this.style.color=this.awJMnbSPM;this.style.backgroundColor=this.awJMNBSpm;if(
awjmNBSPm){this.style.textAlign='center';}if(AWJmnbSPM.indexOf('<')==-1&&aWjmnbspm){AWJmNBSPm=AWjmNBSPm.document.createTextNode(AWJmnbSPM);this.appendChild(AWJmNBSPm);}else {this.innerHTML=AWJmnbSPM;}if(AWJmnbSPM.indexOf('<img')==-1&&eval(AWJmnBSPm+'[3]')){if (awJmnbSpm==1&&awjmnBSPM){aWJMnBspm=AwjmnBSpm;AWJmNBSPM=AWJmnbSPm-12;AWJmnBSPM=AWJmnbsPM-7;aWJMnbspm=10;aWJMNbspm=5;}else{aWJMnBspm=AwjmnbSPm;AWJmNBSPM=AWJmnbSPm-7;AWJmnBSPM=AWJmnbsPM/2-5;aWJMnbspm=5;aWJMNbspm=10;}if(aWjmnbspm){AWJmNBSPm=AWjmNBSPm.document.createElement('img');this.appendChild(AWJmNBSPm);AWJmNBSPm.style.position='absolute';AWJmNBSPm.src=aWJMnBspm;AWJmNBSPm.style.width=aWJMnbspm;AWJmNBSPm.style.height=aWJMNbspm;AWJmNBSPm.style.top=AWJmnBSPM;AWJmNBSPm.style.left=AWJmNBSPM;}else{this.innerHTML=AWJmnbSPM+"<div style='position:absolute;left:"+AWJmNBSPM+";top:"+AWJmnBSPM+";width:"+aWJMnbspm+";height:"+aWJMNbspm+";visibility:inherit'><img src='"+aWJMnBspm+"'></div>";}}if(aWjmNbspm){this.onmouseover=awjMNBSPm;this.onmouseout=awjMnBSPM;this.onclick=awjMnbSPM;}else{this.addEventListener('mouseover',awjMNBSPm,false);this.addEventListener('mouseout',awjMnBSPM,false);this.addEventListener('click',awjMnbSPM,false);}}else{var AWJmnBSPM,AWJmNBSPM,aWJMnbspm,aWJMNbspm,aWJMnBspm;this.awJMnBSPm=eval(AWJmnBSPm+'[0]');if(AwjmnbSpm&&this.awJMnBSPm.indexOf('<')==-1&&!
awjmNBSPm)this.awJMnBSPm='&nbsp\;'+this.awJMnBSPm;if(awjmnBSPm)this.awJMnBSPm=this.awJMnBSPm.bold();if(awjmnbSPM)this.awJMnBSPm=this.awJMnBSPm.italics();this.
AWJmnbSpm=this.awJMnBSPm;this.awJMnBSPm=this.awJMnBSPm.fontcolor(awjmnbsPm);this.
AWJmnbSpm=this.
AWJmnbSpm.fontcolor(awjmNBspm);this.awJMnBSPm=awJmNBSpm+"<font face='"+awjmnbsPM+"' point-size='"+awjmNBSpm+"' color='"+awjmnbsPm+"'>"+this.awJMnBSPm+awJmnBSPm;this.
AWJmnbSpm=awJmNBSpm+"<font face='"+awjmnbsPM+"' point-size='"+awjmNBSpm+"' color='"+awjmNBspm+"'>"+this.
AWJmnbSpm+awJmnBSPm;this.awJMNBSpm=awjmnBspm;this.AWJmnBspm=awjmnbSpm;this.visibility='inherit';this.aWJmNbspm=null;this.aWJmnbsPm=AWJmNBSpm;this.bgColor=awjmnBspm;this.resizeTo(AWJmnbSPm,AWJmnbsPM);this.document.write(this.awJMnBSPm);this.document.close();this.aWJMnbSpm=new Layer(AWJmnbSPm,AWjmnbSpm);this.aWJMnbSpm.visibility='inherit';this.aWJMnbSpm.AWJmNbspm=awJmnbSpm;this.aWJMnbSpm.awJMnbSPm=eval(AWJmnBSPm+'[1]');this.aWJMnbSpm.AWJmnBSpm=eval(AWJmnBSPm+'[2]');this.aWJMnbSpm.onmouseover=awjMNBSPm;this.aWJMnbSpm.onmouseout=awjMnBSPM;this.aWJMnbSpm.captureEvents(Event.MOUSEUP);this.aWJMnbSpm.onmouseup=awjMnbSPM;this.aWJMnbSpm.awJMnbsPM=this;this.aWJMnbSpm.
awJMNBSPM=AWjmnbSpm;this.aWJMnbSpm.resizeTo(AWJmnbSPm,AWJmnbsPM);if(this.awJMnBSPm.indexOf('<img')==-1 &&eval(AWJmnBSPm+'[3]')){this.aWJMnbSpm.aWJMnbsPm=new Layer(10,this.aWJMnbSpm);this.aWJMnbSpm.aWJMnbsPm.visibility='inherit';if (awJmnbSpm==1&&awjmnBSPM){aWJMnBspm=AwjmnBSpm;AWJmNBSPM=AWJmnbSPm-12;AWJmnBSPM=AWJmnbsPM-7;aWJMnbspm=10;aWJMNbspm=5;}else{aWJMnBspm=AwjmnbSPm;AWJmNBSPM=AWJmnbSPm-7;AWJmnBSPM=AWJmnbsPM/2-5;aWJMnbspm=5;aWJMNbspm=10;}this.aWJMnbSpm.aWJMnbsPm.left=AWJmNBSPM;this.aWJMnbSpm.aWJMnbsPm.top=AWJmnBSPM;this.aWJMnbSpm.aWJMnbsPm.width=aWJMnbspm;this.aWJMnbSpm.aWJMnbsPm.height=aWJMNbspm;this.aWJMnbSpm.aWJMnbsPm.document.write("<img src='"+aWJMnBspm+"'>");this.aWJMnbSpm.aWJMnbsPm.document.close();}}}function AWjmNbspm(){if (aWjmNbspm){aWjmnbsPM = aWjmNBspm.document.body.clientWidth;aWjmNBSpm = aWjmNBspm.document.body.clientHeight;aWjmnBSPm = aWjmnBSpm.document.body.clientWidth;aWjmnbSPM = aWjmnBSpm.document.body.clientHeightt;}if (aWjmnbspM){aWjmnbsPM = aWjmNBspm.innerWidth;aWjmNBSpm = aWjmNBspm.innerHeight;aWjmnBSPm = aWjmnBSpm.innerWidth;aWjmnbSPM = aWjmnBSpm.innerHeight;		}if (aWjmnbsPm){awjMnBspm.document.location.reload();}if(awjmNBSPM)awjMNBspm();if(Awjmnbspm)awjMnBSpm();awjMNBSpm(awJmnbsPM,AwjmNbspm,AwjmnBspm);}function 
AWjmnBspm(){if (typeof(awJmnBSpm)!='undefined'&&awJmnBSpm) clearTimeout(awJmnBSpm);if (typeof(awJmnbSPm)!='undefined'&&awJmnbSPm)clearTimeout(awJmnbSPm);aWjmNBSPm=0;
aWjmNBSPM=0;if (aWjmnbsPm){awJmnbsPM.visibility=awJmnBSPM;}else{awJmnbsPM.style.visibility=awJmnBSPM;	}}


	


